version: "3.9"

services:
  course-management-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Database=Host=course-management-db;Port=5432;Database=course_management;User Id=postgres;Password=Abcd1234!;
    ports:
      - "8080:8080"
      - "8088:8088"
  
  course-management-db:
    environment:
      - POSTGRES_DB=course_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Abcd1234!
    volumes:
      - ./.container/database:/var/lib/postgresql/data