// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CourseManagement.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddStaffStudent : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_classes_users_created_by",
                schema: "public",
                table: "classes");

            migrationBuilder.DropForeignKey(
                name: "fk_courses_users_created_by",
                schema: "public",
                table: "courses");

            migrationBuilder.DropColumn(
                name: "first_name",
                schema: "public",
                table: "users");

            migrationBuilder.DropColumn(
                name: "last_name",
                schema: "public",
                table: "users");

            migrationBuilder.RenameColumn(
                name: "name",
                schema: "public",
                table: "courses",
                newName: "title");

            migrationBuilder.RenameColumn(
                name: "created_by",
                schema: "public",
                table: "courses",
                newName: "staff_id");

            migrationBuilder.RenameIndex(
                name: "ix_courses_name",
                schema: "public",
                table: "courses",
                newName: "ix_courses_title");

            migrationBuilder.RenameIndex(
                name: "ix_courses_created_by",
                schema: "public",
                table: "courses",
                newName: "ix_courses_staff_id");

            migrationBuilder.RenameColumn(
                name: "created_by",
                schema: "public",
                table: "course_classes",
                newName: "staff_id");

            migrationBuilder.RenameColumn(
                name: "name",
                schema: "public",
                table: "classes",
                newName: "title");

            migrationBuilder.RenameColumn(
                name: "created_by",
                schema: "public",
                table: "classes",
                newName: "staff_id");

            migrationBuilder.RenameIndex(
                name: "ix_classes_name",
                schema: "public",
                table: "classes",
                newName: "ix_classes_title");

            migrationBuilder.RenameIndex(
                name: "ix_classes_created_by",
                schema: "public",
                table: "classes",
                newName: "ix_classes_staff_id");

            migrationBuilder.CreateTable(
                name: "staffs",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    first_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    last_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    department = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    staff_id = table.Column<Guid>(type: "uuid", nullable: true),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_staffs", x => x.id);
                    table.ForeignKey(
                        name: "fk_staffs_staffs_staff_id",
                        column: x => x.staff_id,
                        principalSchema: "public",
                        principalTable: "staffs",
                        principalColumn: "id");
                    table.ForeignKey(
                        name: "fk_staffs_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "public",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "students",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    first_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    last_name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    staff_id = table.Column<Guid>(type: "uuid", nullable: false),
                    is_deleted = table.Column<bool>(type: "boolean", nullable: false),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_students", x => x.id);
                    table.ForeignKey(
                        name: "fk_students_staffs_staff_id",
                        column: x => x.staff_id,
                        principalSchema: "public",
                        principalTable: "staffs",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_students_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "public",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_course_classes_staff_id",
                schema: "public",
                table: "course_classes",
                column: "staff_id");

            migrationBuilder.CreateIndex(
                name: "ix_staffs_staff_id",
                schema: "public",
                table: "staffs",
                column: "staff_id");

            migrationBuilder.CreateIndex(
                name: "ix_staffs_user_id",
                schema: "public",
                table: "staffs",
                column: "user_id",
                unique: true,
                filter: "\"is_deleted\" = false");

            migrationBuilder.CreateIndex(
                name: "ix_students_staff_id",
                schema: "public",
                table: "students",
                column: "staff_id");

            migrationBuilder.CreateIndex(
                name: "ix_students_user_id",
                schema: "public",
                table: "students",
                column: "user_id",
                unique: true,
                filter: "\"is_deleted\" = false");

            migrationBuilder.AddForeignKey(
                name: "fk_classes_staffs_staff_id",
                schema: "public",
                table: "classes",
                column: "staff_id",
                principalSchema: "public",
                principalTable: "staffs",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_course_classes_staffs_staff_id",
                schema: "public",
                table: "course_classes",
                column: "staff_id",
                principalSchema: "public",
                principalTable: "staffs",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_courses_staffs_staff_id",
                schema: "public",
                table: "courses",
                column: "staff_id",
                principalSchema: "public",
                principalTable: "staffs",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_classes_staffs_staff_id",
                schema: "public",
                table: "classes");

            migrationBuilder.DropForeignKey(
                name: "fk_course_classes_staffs_staff_id",
                schema: "public",
                table: "course_classes");

            migrationBuilder.DropForeignKey(
                name: "fk_courses_staffs_staff_id",
                schema: "public",
                table: "courses");

            migrationBuilder.DropTable(
                name: "students",
                schema: "public");

            migrationBuilder.DropTable(
                name: "staffs",
                schema: "public");

            migrationBuilder.DropIndex(
                name: "ix_course_classes_staff_id",
                schema: "public",
                table: "course_classes");

            migrationBuilder.RenameColumn(
                name: "title",
                schema: "public",
                table: "courses",
                newName: "name");

            migrationBuilder.RenameColumn(
                name: "staff_id",
                schema: "public",
                table: "courses",
                newName: "created_by");

            migrationBuilder.RenameIndex(
                name: "ix_courses_title",
                schema: "public",
                table: "courses",
                newName: "ix_courses_name");

            migrationBuilder.RenameIndex(
                name: "ix_courses_staff_id",
                schema: "public",
                table: "courses",
                newName: "ix_courses_created_by");

            migrationBuilder.RenameColumn(
                name: "staff_id",
                schema: "public",
                table: "course_classes",
                newName: "created_by");

            migrationBuilder.RenameColumn(
                name: "title",
                schema: "public",
                table: "classes",
                newName: "name");

            migrationBuilder.RenameColumn(
                name: "staff_id",
                schema: "public",
                table: "classes",
                newName: "created_by");

            migrationBuilder.RenameIndex(
                name: "ix_classes_title",
                schema: "public",
                table: "classes",
                newName: "ix_classes_name");

            migrationBuilder.RenameIndex(
                name: "ix_classes_staff_id",
                schema: "public",
                table: "classes",
                newName: "ix_classes_created_by");

            migrationBuilder.AddColumn<string>(
                name: "first_name",
                schema: "public",
                table: "users",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "last_name",
                schema: "public",
                table: "users",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddForeignKey(
                name: "fk_classes_users_created_by",
                schema: "public",
                table: "classes",
                column: "created_by",
                principalSchema: "public",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_courses_users_created_by",
                schema: "public",
                table: "courses",
                column: "created_by",
                principalSchema: "public",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
